name: build-push-update-tag

env:
  REGISTRY: jed.ocir.io

on:
  workflow_call:
    inputs:
      SITE_URL:
        required: false
        type: string
      BASE_API_URL:
        required: false
        type: string
      SENTRY_IGNORE_ERRORS:
        required: false
        type: string
      SENTRY_DEBUG:
        required: false
        type: string
        default: 'false'
      SENTRY_TRACES_SAMPLE_RATE:
        required: false
        type: string
        default: '0.1'
      REPLAYS_ON_ERROR_SAMPLE_RATE:
        required: false
        type: string
        default: '0.1'

    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_TOKEN:
        required: true
      INFRA_REPO_SSH_KEY:
        required: true
      NPM_TOKEN:
        required: true
      SENTRY_DSN:
        required: false

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      sha8: ${{ steps.get-sha8.outputs.sha8 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get short SHA
        id: get-sha8
        run: |
          short_sha=$(echo ${GITHUB_SHA} | cut -c1-8)
          echo "sha8=$short_sha" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/axvp4vawnqyw/${{ github.event.repository.name }}

      - name: Login to REGISTRY
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/axvp4vawnqyw/${{ github.event.repository.name }}:${{ steps.get-sha8.outputs.sha8 }}
          labels: ${{ steps.meta.outputs.labels }}
          # Couldn't find a way to make this accept any arbitrary variables, so it will assign all possible variables
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            SITE_URL=${{ inputs.SITE_URL }}
            BASE_API_URL=${{ inputs.BASE_API_URL }}
            REACT_APP_BASE_API_URL=${{ inputs.BASE_API_URL }}
            REACT_APP_ENVIRONMENT=${{ github.ref_name == 'main' && 'production' || 'development' }}
            REACT_APP_SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            REACT_APP_SENTRY_DEBUG=${{ inputs.SENTRY_DEBUG }}
            REACT_APP_SENTRY_IGNORE_ERRORS=${{ inputs.SENTRY_IGNORE_ERRORS }}
            REACT_APP_SENTRY_TRACES_SAMPLE_RATE=${{ inputs.SENTRY_TRACES_SAMPLE_RATE }}
            REACT_APP_SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE=${{ inputs.REPLAYS_ON_ERROR_SAMPLE_RATE }}

  update-tag:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v3
        with:
          repository: madkol/madkhol-deployment
          ssh-key: "${{ secrets.INFRA_REPO_SSH_KEY }}"
        if: github.event_name != 'pull_request'

      - name: Split repository name
        uses: jungwinter/split@v2
        id: split-repo-name
        with:
          msg: ${{ github.event.repository.name }}
          separator: '-'
          maxsplit: '1'

      - name: Update manifests images tag for dev
        working-directory: helm-releases/${{ steps.split-repo-name.outputs._0 }}/${{ steps.split-repo-name.outputs._1 }}
        run: |
          # Change Helm values image tag
          sed -i --regexp-extended 's|^  tag: "[a-zA-Z0-9]{4,10}"|  tag: "${{ needs.build-push.outputs.sha8 }}"|g' dev.yaml
        if: github.ref_name == 'dev'

      - name: Update manifests images tag for stg
        working-directory: helm-releases/${{ steps.split-repo-name.outputs._0 }}/${{ steps.split-repo-name.outputs._1 }}
        run: |
          # Change Helm values image tag
          sed -i --regexp-extended 's|^  tag: "[a-zA-Z0-9]{4,10}"|  tag: "${{ needs.build-push.outputs.sha8 }}"|g' stg.yaml
        if: github.ref_name == 'stg'

      - name: Update manifests images tag for prod
        working-directory: helm-releases/${{ steps.split-repo-name.outputs._0 }}/${{ steps.split-repo-name.outputs._1 }}
        run: |
          # Change Helm values image tag
          sed -i --regexp-extended 's|^  tag: "[a-zA-Z0-9]{4,10}"|  tag: "${{ needs.build-push.outputs.sha8 }}"|g' prod.yaml
        if: github.ref_name == 'prod'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic changes for helm-releases/${{ steps.split-repo-name.outputs._0 }}/${{ steps.split-repo-name.outputs._1 }}
        if: github.event_name != 'pull_request'
